
### try .. catch

可以透過 try .. catch 來處理例外事件。捕捉到的錯誤事件內容包含這個錯誤的有用資訊，像是錯誤類型、錯誤訊息、發生錯誤的位置等等，方便我們處理所發生的錯誤，避免程式意外的停止。

#### 基本語法

```javascript
try {
  // 可能會拋出錯誤的程式碼
} catch (ex) {
  // 捕獲並處理錯誤
}
```

#### 執行階段錯誤

try 區塊可以捕捉執行階段拋出的錯誤。如果出現錯誤將會執行 catch 區塊中指定的作業。

```javascript
try {
  let x = y + 10;
} catch (ex) {
  console.log("執行失敗：" + ex);
}

// 試試看這個會不會發生錯誤
try {
  let result = 10 / 0;
} catch (ex) {
  console.log("執行失敗：" + ex);
}

```

#### 自定義錯誤 throw

try .. catch 除了捕捉執行時非意料中的事件外，也可以透過 throw 拋出自訂的錯誤事件

```javascript
try {
  let age = 12;
  if (age < 18) {
    throw new Error("年齡不符合要求");
  }
  console.log("歡迎來到遊樂場.");
} catch (ex) {
  console.log(ex.message);
}

```

#### 就算發生錯誤也要使命必達 finally

即使發生錯誤，finally 裡面的程式碼都會被執行。通常用於釋放資源、關閉檔案等結束動作。

```javascript
let file = OpenFile();

try {
  // 使用資源的程式碼
  file.read();

  let x = y + 10;
  console.log("執行不到這一行");
} catch (ex) {
  // 處理錯誤的程式碼
  console.log("執行失敗：" + ex);
} finally {
  // 釋放資源的程式碼
  CloseFile(file);
  console.log("這一行一定會被執行到");
}

```

#### 什麼時候該用 try .. catch

- 呼叫或是連結可能會發生錯誤的外部連結（例如：檔案、網路呼叫或是資料庫連接）。捕獲錯誤後適當地處理這些錯誤（例如：回應錯誤訊息給使用者或資料 Rollback等）。

- 可能會發生例外情況的程式碼（例如：解析JSON / XML、處理使用者輸入資料或調用第三方程式庫等）。可以抓到並處理這些例外情況，避免程式停止或無法正確運行。
